name: Build osmium

on:
  workflow_dispatch:
  push:
    branches: [main, master, develop]
    paths: ['osmium/**']
    tags: ['osmium-*']

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-chain.yml
    with:
      chain-name: osmium
      context-path: ./osmium
      image-name: maximus-chain/osmiumd
    secrets: inherit
